[package]
name = "constellation-fabric"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
bincode.workspace = true
serde_json.workspace = true
thiserror.workspace = true
async-trait.workspace = true
rmp-serde = "1"
ciborium = "0.2"
postcard = { version = "1", features = ["alloc"] }
constellation-core = { path = "../core" }
