[package]
name = "constellation-telemetry"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
rand.workspace = true
ulid = { version = "1", features = ["serde"] }

[dev-dependencies]
tempfile = "3"
scopeguard = "1"
