[package]
name = "constellation-node"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
constellation-core = { path = "../core" }
constellation-fabric = { path = "../fabric" }
constellation-node-derive = { path = "../node-derive" }
constellation-raft = { path = "../raft" }
constellation-telemetry = { path = "../telemetry" }

tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
async-trait.workspace = true
schemars.workspace = true
smart-default.workspace = true
rand.workspace = true

uuid = { version = "1", features = ["v4", "serde"] }
inventory = "0.3"
anyhow = "1"
dashmap = "6"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
