[package]
name = "constellation-raft"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
constellation-fabric = { path = "../fabric" }

tokio.workspace = true
serde.workspace = true
thiserror.workspace = true
async-trait.workspace = true
schemars.workspace = true
smart-default.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
